# Generated by Django 5.0.4 on 2024-04-23 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20210512_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='quesmodel',
            old_name='op1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='quesmodel',
            old_name='op2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='quesmodel',
            old_name='op3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='quesmodel',
            old_name='op4',
            new_name='option4',
        ),
    ]
