# Generated by Django 5.0.4 on 2024-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_rename_ans_quesmodel_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[], default='java', max_length=100),
            preserve_default=False,
        ),
    ]
