# Generated by Django 5.0.4 on 2024-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_alter_quesmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('communication', 'Communication'), ('Emotional', 'Emotional'), ('Ethics', 'Ethics'), ('Sales', 'Sales')], max_length=100),
        ),
    ]
