# Generated by Django 5.0.4 on 2024-05-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_alter_quesmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('communication', 'Communication'), ('emotion', 'Emotion'), ('ethics', 'Ethics'), ('sales', 'Sales')], max_length=100),
        ),
    ]
