# Generated by Django 5.0.4 on 2024-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_alter_quesmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='answer',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default='option1', max_length=50),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[('programming', 'Computer Science'), ('communication', 'Communication Skills'), ('emotion', 'Emotional Intelligence'), ('ethics', 'Ethics'), ('sales', 'Customer Service')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='option1',
            field=models.CharField(default='Option 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='option2',
            field=models.CharField(default='Option 2', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='option3',
            field=models.CharField(default='Option 3', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='option4',
            field=models.CharField(default='Option 4', max_length=200),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
