# Generated by Django 5.0.4 on 2024-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_quesmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('communication skills', 'Communication skills'), ('Emotional intelligennce', 'Emotional intelligennce'), ('Ethics', 'Ethics')], max_length=100),
        ),
    ]
